version: "3.8"
name: sowalnk
services:
  # Backend
  node-app:
    build:
      context: ./sowalnkBackend
      dockerfile: Dockerfile
    container_name: sowalnk-node-app
    ports:
      - 2000:2000
    env_file:
      - ./sowalnkBackend/.env
  # Frontend
  react-app:
    build:
      context: ./Sowalnk
      dockerfile: Dockerfile
    container_name: sowalnk-react-app
    env_file:
      - ./Sowalnk/.env
    ports:
      - 5173:5173
    depends_on:
      - node-app
